/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Compte;
import java.sql.Connection;

/**
 *
 * @author zokum
 */
public class AccueilAdmin extends javax.swing.JFrame {
 Connection cntAP ;
    Compte cpt ;
    
    /**
     * Creates new form AccueilAdmin
     */
    public AccueilAdmin() {
        initComponents();
    }
 public AccueilAdmin(Connection cnt, Compte leCompte) {
            cpt=leCompte;
        
        System.out.println("5"+leCompte.getUnPompier().getNom());
         initComponents();
        

        
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Vehicules = new javax.swing.JButton();
        Pompiers = new javax.swing.JButton();
        Casernes = new javax.swing.JButton();
        Missions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(920, 565));
        setMinimumSize(new java.awt.Dimension(920, 565));

        jPanel1.setBackground(new java.awt.Color(39, 38, 38));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrateur :");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Vehicules.setBackground(new java.awt.Color(39, 38, 38));
        Vehicules.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Vehicules.setForeground(new java.awt.Color(255, 255, 255));
        Vehicules.setText("<html> <head><title></title> </head> <body>  Liste des  <br>  Vehicules </body> </html>");
        Vehicules.setBorder(null);
        Vehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiculesMouseClicked(evt);
            }
        });

        Pompiers.setBackground(new java.awt.Color(39, 38, 38));
        Pompiers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pompiers.setForeground(new java.awt.Color(255, 255, 255));
        Pompiers.setText("<html> <head><title></title> </head> <body>  Liste des <br>  Pompiers </body> </html>");
        Pompiers.setToolTipText("");
        Pompiers.setBorder(null);
        Pompiers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PompiersMouseClicked(evt);
            }
        });

        Casernes.setBackground(new java.awt.Color(39, 38, 38));
        Casernes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Casernes.setForeground(new java.awt.Color(255, 255, 255));
        Casernes.setText("<html> <head><title></title> </head> <body>  Liste des <br>  Casernes </body> </html>");
        Casernes.setBorder(null);
        Casernes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CasernesMouseClicked(evt);
            }
        });

        Missions.setBackground(new java.awt.Color(39, 38, 38));
        Missions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Missions.setForeground(new java.awt.Color(255, 255, 255));
        Missions.setText("<html> <head><title></title> </head> <body>  Liste des <br>  Missions </body> </html>");
        Missions.setBorder(null);
        Missions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MissionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vehicules, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Missions, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Casernes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(Pompiers, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehicules, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Missions, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pompiers, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casernes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(920, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CasernesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasernesMouseClicked
       String msg = jLabel1.getText();
        new ListeCaserne(cpt,msg).setVisible(true);
        dispose();
    }//GEN-LAST:event_CasernesMouseClicked

    private void MissionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MissionsMouseClicked
        String msg = jLabel1.getText();
        new ListeIntervention(cpt,msg).setVisible(true);
        dispose();
    }//GEN-LAST:event_MissionsMouseClicked

    private void VehiculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiculesMouseClicked
       String msg = jLabel1.getText();
        new ListeVehicules(cpt,msg).setVisible(true);
        dispose();
    }//GEN-LAST:event_VehiculesMouseClicked

    private void PompiersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PompiersMouseClicked
        String msg = jLabel1.getText();
        new ListePompier(cpt,msg).setVisible(true);
        dispose();
    }//GEN-LAST:event_PompiersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new AccueilAdmin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casernes;
    private javax.swing.JButton Missions;
    private javax.swing.JButton Pompiers;
    private javax.swing.JButton Vehicules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
