/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Dao.CaserneDAO;
import Dao.ConnexionBdd;
import Dao.PompierDAO;
import Modele.Caserne;
import Modele.Compte;
import Modele.Pompier;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author ts1sio
 */
public class ListeCaserne extends javax.swing.JFrame {
     Connection cnt= ConnexionBdd.ouvrirConnexion() ;
    Compte cpt;
    /**
     * Creates new form ListeCaserne
     */
    public ListeCaserne() {
        initComponents();
        
       
         
    }
    public ListeCaserne(Compte leCompte, String msg){
        initComponents();
        msgLabel.setVisible(false);
        msgLabel.setText(msg);
        cpt=leCompte;
        listeCaserne.removeAllItems();
        remplirJboxCaserne();
        //afficheInfo();
         
    }
    
    
     public void remplirJboxCaserne(){
        ArrayList<Caserne> caserne= CaserneDAO.getCaserneNom(cnt);
       
        for(int i=0 ; i<caserne.size();i++){
           listeCaserne.addItem(caserne.get(i).getNomCas());
        } 
        System.out.println(listeCaserne);
     }
     
     private Caserne selectPage(){
        String list= listeCaserne.getSelectedItem().toString();
        Caserne uneCaserne=CaserneDAO.afficheInfo(cnt,list);
           return uneCaserne;
        }
    public void afficheInfo(){
            Caserne laCaserne=selectPage();
            Caslabel.setText(laCaserne.getIdcas().toString());
            villeLabel.setText(laCaserne.getVilleCas());
            nomlabel.setText(laCaserne.getNomCas());
            cpLabel.setText(laCaserne.getCpCas().toString());
            rueLabel.setText(laCaserne.getRueCas());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casVille2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        listeCaserne = new javax.swing.JComboBox<>();
        casId = new javax.swing.JLabel();
        casNom = new javax.swing.JLabel();
        casVille = new javax.swing.JLabel();
        casVille1 = new javax.swing.JLabel();
        casVille3 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        Caslabel = new javax.swing.JLabel();
        villeLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        nomlabel = new javax.swing.JLabel();
        rueLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        casVille2.setBackground(new java.awt.Color(39, 38, 38));
        casVille2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        casVille2.setForeground(new java.awt.Color(255, 255, 255));
        casVille2.setText("Ville :");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(936, 604));
        setMinimumSize(new java.awt.Dimension(936, 604));

        jPanel1.setBackground(new java.awt.Color(39, 38, 38));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(936, 604));
        jPanel1.setMinimumSize(new java.awt.Dimension(936, 604));

        jLabel1.setBackground(new java.awt.Color(39, 38, 38));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liste des casernes :");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        listeCaserne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        casId.setBackground(new java.awt.Color(39, 38, 38));
        casId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        casId.setForeground(new java.awt.Color(255, 255, 255));
        casId.setText("Caserne id :");

        casNom.setBackground(new java.awt.Color(39, 38, 38));
        casNom.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        casNom.setForeground(new java.awt.Color(255, 255, 255));
        casNom.setText("Nom :");

        casVille.setBackground(new java.awt.Color(39, 38, 38));
        casVille.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        casVille.setForeground(new java.awt.Color(255, 255, 255));
        casVille.setText("Code postal :");

        casVille1.setBackground(new java.awt.Color(39, 38, 38));
        casVille1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        casVille1.setForeground(new java.awt.Color(255, 255, 255));
        casVille1.setText("Ville :");

        casVille3.setBackground(new java.awt.Color(39, 38, 38));
        casVille3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        casVille3.setForeground(new java.awt.Color(255, 255, 255));
        casVille3.setText("Rue :");

        Retour.setBackground(new java.awt.Color(39, 38, 38));
        Retour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Retour.setForeground(new java.awt.Color(255, 255, 255));
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        msgLabel.setText("jLabel11");

        Caslabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Caslabel.setText("jLabel2");

        villeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        villeLabel.setText("jLabel2");

        cpLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpLabel.setText("jLabel2");

        nomlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomlabel.setText("jLabel2");

        rueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rueLabel.setText("jLabel2");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(casVille1)
                            .addComponent(casNom)
                            .addComponent(casId)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(casVille3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addComponent(listeCaserne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(167, 167, 167)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casVille)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(msgLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(villeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Caslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(msgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeCaserne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casId)
                    .addComponent(Caslabel))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casNom)
                    .addComponent(nomlabel))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casVille1)
                    .addComponent(villeLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casVille)
                            .addComponent(cpLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casVille3)
                    .addComponent(rueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(936, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        this.setVisible(false);

        if (msgLabel.getText().equals("Responsable Pompier :")){
            new AccueilResp(cnt,cpt).setVisible(true);

        } else if (msgLabel.getText().equals("Administrateur :")){
            new AccueilAdmin().setVisible(true);

        }
        
    }//GEN-LAST:event_RetourActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        afficheInfo();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeCaserne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeCaserne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeCaserne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeCaserne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeCaserne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caslabel;
    private javax.swing.JButton Retour;
    private javax.swing.JLabel casId;
    private javax.swing.JLabel casNom;
    private javax.swing.JLabel casVille;
    private javax.swing.JLabel casVille1;
    private javax.swing.JLabel casVille2;
    private javax.swing.JLabel casVille3;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> listeCaserne;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel nomlabel;
    private javax.swing.JLabel rueLabel;
    private javax.swing.JLabel villeLabel;
    // End of variables declaration//GEN-END:variables
}
