/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Dao.ConnexionBdd;
import Dao.PompierDAO;
import static Dao.PompierDAO.getMesInterventions;
import Modele.Compte;
import Modele.Intervention;
import Modele.Pompier;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;



/**
 *
 * @author Maxime Bellegueille
 */
public class ListeIntervention extends javax.swing.JFrame {
    Connection cnt = ConnexionBdd.ouvrirConnexion();
    Compte cpt;
    

    /**
     * Creates new form ListeIntervention
     */
    public ListeIntervention() {
        initComponents();
        
        
      
    }
   
    public ListeIntervention(Compte leCompte, String msg ){
        initComponents();
        msgLabel.setVisible(false);
        msgLabel.setText(msg);
         cpt=leCompte;
         
         separatorFalse();
         cleanInfo();
         
        remplirJbox();
         
        
        if(msgLabel.getText().equals("Pompier :")){
            Modifier.setVisible(false);
            Valider.setVisible(false);
            Delete.setVisible(false);
        }
        
        
        
      
       
        
       
    }
    
    public void remplirJbox(){
        ArrayList<Intervention> intervention= PompierDAO.getMesInterventions(cnt,cpt.getUnPompier().getId());
       
        for(int i=0 ; i<intervention.size();i++){
           boxInter.addItem(intervention.get(i).getDate());
        } 
     }
    
   /*private Intervention selectPage(){
        String list= boxInter.getSelectedItem().toString();
        Intervention uneinter=PompierDAO.afficheInfo(cnt,list);
           return unPompiera;
        }
    
     public void afficheInfo(){
            Pompier lePompier=selectPage();
            nomLabel.setText(lePompier.getNom());
            prenomLabel.setText(lePompier.getPrenom());
            sexeLabel.setText(lePompier.getSexe());
            dateLabel.setText(lePompier.getDteNaissance());
            telLabel.setText(lePompier.getTel());
            matLabel.setText(lePompier.getMatricule());
            bipLabel.setText(lePompier.getBip());
            /*gradeLabel.setText(lePompier.getUnGrade().getLibelle());
            casLabel.setText(lePompier.getUneCaserne().getNomCas());
        }*/
    
    public void separatorFalse(){
        jSeparator10.setVisible(false);
        jSeparator12.setVisible(false);
        jSeparator13.setVisible(false);
        jSeparator14.setVisible(false);
        jSeparator15.setVisible(false);
        jSeparator16.setVisible(false);
        jSeparator17.setVisible(false);
        jSeparator18.setVisible(false);
           
    }
    
    public void cleanInfo(){
        dateLabel.setText("");
        dureeLabel.setText("");
        villeLabel.setText("");
        typeLabel.setText("");
        adresseLabel.setText("");
        descLabel.setText("");
        heureLabel.setText("");
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator13 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        boxInter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Retour = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        descLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpompier = new javax.swing.JList<>();
        msgLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        villeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        dureeLabel = new javax.swing.JLabel();
        heureLabel = new javax.swing.JLabel();

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 38, 38));
        jPanel1.setMaximumSize(new java.awt.Dimension(936, 604));
        jPanel1.setMinimumSize(new java.awt.Dimension(936, 604));
        jPanel1.setPreferredSize(new java.awt.Dimension(936, 604));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(39, 38, 38));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liste des interventions :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(86, 60, 214, 25);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(86, 91, 214, 10);

        boxInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxInterActionPerformed(evt);
            }
        });
        jPanel1.add(boxInter);
        boxInter.setBounds(90, 110, 214, 24);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(333, 130, 46, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pompiers :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 291, 77, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ville :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 170, 43, 20);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adresse :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 130, 70, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Heure :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 170, 53, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Durée :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(585, 206, 60, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(336, 206, 43, 20);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 300, 90, 20);

        Delete.setBackground(new java.awt.Color(39, 38, 38));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete.png"))); // NOI18N
        Delete.setBorder(null);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(397, 506, 60, 60);

        Retour.setBackground(new java.awt.Color(39, 38, 38));
        Retour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Retour.setForeground(new java.awt.Color(255, 255, 255));
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        jPanel1.add(Retour);
        Retour.setBounds(750, 500, 98, 40);

        jButton1.setBackground(new java.awt.Color(39, 38, 38));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reload");
        jButton1.setMaximumSize(new java.awt.Dimension(97, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(97, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(97, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 520, 150, 32);

        Valider.setBackground(new java.awt.Color(39, 38, 38));
        Valider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Valider.setForeground(new java.awt.Color(255, 255, 255));
        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel1.add(Valider);
        Valider.setBounds(39, 424, 130, 32);

        Modifier.setBackground(new java.awt.Color(39, 38, 38));
        Modifier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        jPanel1.add(Modifier);
        Modifier.setBounds(40, 510, 130, 32);

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10);
        jSeparator10.setBounds(380, 230, 160, 10);

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator12);
        jSeparator12.setBounds(385, 150, 160, 10);

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator14);
        jSeparator14.setBounds(380, 190, 160, 10);

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator15);
        jSeparator15.setBounds(640, 190, 160, 10);

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator16);
        jSeparator16.setBounds(635, 226, 160, 10);

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator18);
        jSeparator18.setBounds(650, 150, 160, 10);

        descLabel.setBackground(new java.awt.Color(255, 255, 255));
        descLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descLabel.setForeground(new java.awt.Color(255, 255, 255));
        descLabel.setText("jLabel10");
        jPanel1.add(descLabel);
        descLabel.setBounds(690, 311, 230, 220);

        jScrollPane1.setBorder(null);

        listpompier.setBackground(new java.awt.Color(39, 38, 38));
        listpompier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listpompier.setForeground(new java.awt.Color(255, 255, 255));
        listpompier.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listpompier.setEnabled(false);
        jScrollPane1.setViewportView(listpompier);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(420, 301, 140, 160);

        msgLabel.setText("jLabel11");
        jPanel1.add(msgLabel);
        msgLabel.setBounds(746, 27, 40, 15);

        typeLabel.setBackground(new java.awt.Color(255, 255, 255));
        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("typeLabel");
        jPanel1.add(typeLabel);
        typeLabel.setBounds(391, 132, 160, 20);

        villeLabel.setBackground(new java.awt.Color(255, 255, 255));
        villeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        villeLabel.setForeground(new java.awt.Color(255, 255, 255));
        villeLabel.setText("villeLabel");
        jPanel1.add(villeLabel);
        villeLabel.setBounds(380, 170, 160, 20);

        dateLabel.setBackground(new java.awt.Color(255, 255, 255));
        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("dateLabel");
        jPanel1.add(dateLabel);
        dateLabel.setBounds(380, 210, 160, 20);

        adresseLabel.setBackground(new java.awt.Color(255, 255, 255));
        adresseLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        adresseLabel.setForeground(new java.awt.Color(255, 255, 255));
        adresseLabel.setText("adresseLabel");
        jPanel1.add(adresseLabel);
        adresseLabel.setBounds(650, 132, 160, 20);

        dureeLabel.setBackground(new java.awt.Color(255, 255, 255));
        dureeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dureeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dureeLabel.setText("dureeLabel");
        jPanel1.add(dureeLabel);
        dureeLabel.setBounds(640, 210, 160, 20);

        heureLabel.setBackground(new java.awt.Color(255, 255, 255));
        heureLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        heureLabel.setForeground(new java.awt.Color(255, 255, 255));
        heureLabel.setText("heureLabel");
        jPanel1.add(heureLabel);
        heureLabel.setBounds(640, 170, 160, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(936, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        /*separatorTrue();

        String typeL= typeLabel.getText();
        String dateL= dateLabel.getText();
        String sexeL= sexeLabel.getText();
        String telL= telLabel.getText();
        String casL= casLabel.getText();
        String foncL= foncLabel.getText();
        String dateL= dateLabel.getText();
        String matL= matLabel.getText();
        String gradeL= gradeLabel.getText();
        String bipL= bipLabel.getText();

        labelFalse();

        typeField.setText(typeL);
        dateField.setText(dateL);
        sexeField.setText(sexeL);
        telField.setText(telL);
        casField.setText(casL);
        foncField.setText(foncL);
        dateField.setText(dateL);
        matField.setText(matL);
        gradeField.setText(gradeL);
        bipField.setText(bipL);

        jLabel14.setText("Modif");*/
    }//GEN-LAST:event_ModifierActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed

        /* fieldFalse();
        separatorFalse();
        labelTrue();

        Pompier p = new Pompier();
        p.setDate(dateField.getText());
        p.setType(typeField.getText());
        p.setHarrive(HarriveField.getText());
        p.setHappel(HappelField.getText());
        p.setDuree(dureeField.getText());
        p.setAdresse(adresseField.getText());
        p.setVille(villeField.getText());
        p.setCp(cpField.getText());
        p.setDesc(descField.getText());

        /* p.setUneCaserne(op);
        p.setFonc(concField.getText());

        p.setGrade(gradeField.getText());*/

        /* String listeJBox = jComboBox.getSelectedItem().toString();
        String date= dateField.getText();
        String type=typeField.getText();
        String sexe=sexeField.getText();
        String tel=telField.getText();
        String Duree=casField.getText();
        String fonc=foncField.getText();
        String mat=matField.getText();
        String grade=gradeField.getText();
        String bip=bipField.getText();
        String verif=jLabel14.getText();

        if(verif.equals("Modif")){
            if(date.equals("") || type.equals("")|| Harrive.equals("")|| Happel.equals("")|| bip.equals("")|| sexe.equals("") || tel.equals("") || cas.equals("") || fonc.equals("") || mat.equals("")){
                JOptionPane.showMessageDialog(this,"Modification échoué car tout les élements ne sont pas remplis !");
            }else{

            }
            fillCombo();
        }

        else if(verif.equals("Ajout")){
            if(date.equals("") || type.equals("")||  date.equals("")|| bip.equals("")){
                JOptionPane.showMessageDialog(this,"L'ajout a échoué car tout les élements ne sont pas remplis !");
            }else{
                PompierDAO.addPompier(cnt, p);
            }

            /* insertPompier( sexe ,  tel,  grade,  cas,  date,  type,  date,  bip,  mat , fonc);*/

            /*}

        Valider.setVisible(false);*/
    }//GEN-LAST:event_ValiderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* listeNom();
        cleanInfo();
        fillCombo();*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        this.setVisible(false);

        if (msgLabel.getText().equals("Responsable Pompier :")){
            new AccueilResp(cnt,cpt).setVisible(true);

        } else if (msgLabel.getText().equals("Administrateur :")){
            new AccueilAdmin().setVisible(true);

        }
        else if (msgLabel.getText().equals("Pompier :")){
            new AccueilPomp(cnt,cpt).setVisible(true);
        }

    }//GEN-LAST:event_RetourActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // String list = jComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_DeleteActionPerformed

    private void boxInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxInterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeIntervention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeIntervention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeIntervention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeIntervention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeIntervention().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JComboBox<String> boxInter;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel dureeLabel;
    private javax.swing.JLabel heureLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JList<String> listpompier;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel villeLabel;
    // End of variables declaration//GEN-END:variables
}
